// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyrelkxqvxzsqwzkhekd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5cmVsa3hxdnh6c3F3emtoZWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyMzA1ODQsImV4cCI6MjA5MDgwNjU4NH0._tCBGPbt62hyM616BlXZRCyrLZvOKQQ0fPSpxWS3dpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});